#!/bin/bash
#
# Let's Encrypt helper for pbx3sbc-admin (CLI + Filament Certificates panel).
# Run as root (installer) or via sudo from www-data (sudoers).
#
# Usage:
#   le-admin-cert.sh status <fqdn>
#   le-admin-cert.sh setup <fqdn> <email> <webroot>
#   le-admin-cert.sh renew <fqdn>
#   le-admin-cert.sh apply-nginx <fqdn> <webroot> <php_fpm_socket>
#
set -euo pipefail

json_escape() {
    python3 -c 'import json,sys; print(json.dumps(sys.stdin.read().rstrip("\n")))' <<<"$1"
}

require_root() {
    if [[ ${EUID} -ne 0 ]]; then
        echo "Error: must run as root (or via sudo)" >&2
        exit 1
    fi
}

validate_fqdn() {
    local f="$1"
    if [[ -z "$f" ]] || [[ "$f" != *.* ]] || [[ "$f" == *[[:space:]]* ]] || [[ "$f" == */* ]]; then
        echo "Error: invalid FQDN: ${f}" >&2
        exit 1
    fi
}

validate_email() {
    local e="$1"
    if [[ -z "$e" ]] || [[ "$e" != *@*.* ]] || [[ "$e" == *[[:space:]]* ]]; then
        echo "Error: invalid email: ${e}" >&2
        exit 1
    fi
}

cmd_status() {
    local fqdn="$1"
    validate_fqdn "$fqdn"
    local live="/etc/letsencrypt/live/${fqdn}"
    if [[ ! -f "${live}/fullchain.pem" ]]; then
        printf '{"configured":false,"domain":%s}\n' "$(json_escape "$fqdn")"
        return 0
    fi
    local expires issuer
    expires=$(openssl x509 -in "${live}/fullchain.pem" -noout -enddate 2>/dev/null | sed 's/^notAfter=//' || true)
    issuer=$(openssl x509 -in "${live}/fullchain.pem" -noout -issuer 2>/dev/null | sed 's/^issuer=//' || true)
    printf '{"configured":true,"domain":%s,"expires_at":%s,"issuer":%s}\n' \
        "$(json_escape "$fqdn")" \
        "$(json_escape "${expires:-}")" \
        "$(json_escape "${issuer:-}")"
}

ensure_ssl_snippets() {
    mkdir -p /etc/letsencrypt
    if [[ ! -f /etc/letsencrypt/options-ssl-nginx.conf ]]; then
        cat > /etc/letsencrypt/options-ssl-nginx.conf <<'EOF'
ssl_session_cache shared:le_nginx_SSL:10m;
ssl_session_timeout 1440m;
ssl_session_tickets off;
ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;
ssl_ciphers "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384";
EOF
    fi
    if [[ ! -f /etc/letsencrypt/ssl-dhparams.pem ]]; then
        openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048
    fi
}

cmd_apply_nginx() {
    require_root
    local fqdn="$1"
    local webroot="$2"
    local php_sock="${3:-}"
    local cert_fullchain="${4:-/etc/letsencrypt/live/${fqdn}/fullchain.pem}"
    local cert_key="${5:-/etc/letsencrypt/live/${fqdn}/privkey.pem}"
    validate_fqdn "$fqdn"
    if [[ -z "$webroot" || ! -d "$webroot" ]]; then
        echo "Error: webroot directory required" >&2
        exit 1
    fi
    if [[ -z "$php_sock" ]]; then
        php_sock=$(ls /run/php/php*-fpm.sock 2>/dev/null | head -1 || true)
    fi
    if [[ -z "$php_sock" || ! -S "$php_sock" ]]; then
        echo "Error: PHP-FPM socket not found" >&2
        exit 1
    fi
    if [[ ! -f "$cert_fullchain" || ! -f "$cert_key" ]]; then
        echo "Error: certificate files missing" >&2
        exit 1
    fi
    ensure_ssl_snippets
    local conf="/etc/nginx/sites-available/pbx3sbc-admin"
    # Prefer LE include/dhparam only when using Let's Encrypt paths
    local ssl_extra=""
    if [[ "$cert_fullchain" == /etc/letsencrypt/* ]]; then
        ssl_extra="    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;"
    else
        ssl_extra="    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;"
    fi
    cat > "$conf" <<EOF
# pbx3sbc-admin — HTTP ACME + redirect to HTTPS (generated by le-admin-cert.sh)
server {
    listen 80;
    listen [::]:80;
    server_name ${fqdn};

    root ${webroot};

    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        try_files \$uri =404;
    }

    # Fleet warm-sync hits member public IPs over HTTP (LE cert is FQDN-only).
    location ^~ /api/ {
        try_files \$uri /index.php?\$query_string;
    }

    location ~ ^/index\\.php(/|$) {
        fastcgi_pass unix:${php_sock};
        fastcgi_param SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${fqdn};

    root ${webroot};

    ssl_certificate     ${cert_fullchain};
    ssl_certificate_key ${cert_key};
${ssl_extra}

    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    index index.php;
    charset utf-8;

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    error_page 404 /index.php;

    location ~ \\.php\$ {
        fastcgi_pass unix:${php_sock};
        fastcgi_param SCRIPT_FILENAME \$realpath_root\$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param HTTPS on;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\\.(?!well-known).* {
        deny all;
    }
}
EOF
    ln -sfn "$conf" /etc/nginx/sites-enabled/pbx3sbc-admin
    rm -f /etc/nginx/sites-enabled/default
    nginx -t
    systemctl reload nginx

    mkdir -p /etc/letsencrypt/renewal-hooks/deploy
    cat > /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh <<'HOOK'
#!/bin/bash
systemctl reload nginx
HOOK
    chmod +x /etc/letsencrypt/renewal-hooks/deploy/reload-nginx.sh
}

set_app_url_https() {
    local fqdn="$1"
    local webroot="$2"
    local admin_dir envf
    admin_dir=$(dirname "$webroot")
    envf="${admin_dir}/.env"
    if [[ -f "$envf" ]]; then
        if grep -q '^APP_URL=' "$envf"; then
            sed -i "s|^APP_URL=.*|APP_URL=https://${fqdn}|" "$envf"
        else
            echo "APP_URL=https://${fqdn}" >> "$envf"
        fi
        if [[ -x "${admin_dir}/artisan" ]]; then
            sudo -u www-data -H php "${admin_dir}/artisan" config:clear 2>/dev/null \
                || php "${admin_dir}/artisan" config:clear 2>/dev/null \
                || true
        fi
    fi
}

cmd_setup() {
    require_root
    local fqdn="$1"
    local email="$2"
    local webroot="$3"
    validate_fqdn "$fqdn"
    validate_email "$email"
    if [[ -z "$webroot" || ! -d "$webroot" ]]; then
        echo "Error: webroot directory required" >&2
        exit 1
    fi
    if [[ ! -f /etc/nginx/sites-available/pbx3sbc-admin ]]; then
        echo "Error: nginx site pbx3sbc-admin missing — run admin install first" >&2
        exit 1
    fi
    if ! command -v certbot >/dev/null 2>&1; then
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -qq
        apt-get install -y -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" certbot >/dev/null
    fi
    certbot certonly --webroot \
        -w "$webroot" \
        -d "$fqdn" \
        --non-interactive --agree-tos -m "$email" \
        --keep-until-expiring
    local php_sock
    php_sock=$(ls /run/php/php*-fpm.sock 2>/dev/null | head -1 || true)
    cmd_apply_nginx "$fqdn" "$webroot" "$php_sock"
    set_app_url_https "$fqdn" "$webroot"
    cmd_status "$fqdn"
}

cmd_renew() {
    require_root
    local fqdn="$1"
    validate_fqdn "$fqdn"
    if [[ ! -f "/etc/letsencrypt/live/${fqdn}/fullchain.pem" ]]; then
        echo "Error: no certificate for ${fqdn}" >&2
        exit 1
    fi
    certbot renew --cert-name "$fqdn" --non-interactive
    systemctl reload nginx 2>/dev/null || true
    cmd_status "$fqdn"
}

cmd_custom_install() {
    require_root
    local fqdn="$1"
    local cert_src="$2"
    local key_src="$3"
    local webroot="$4"
    validate_fqdn "$fqdn"
    if [[ ! -f "$cert_src" || ! -f "$key_src" ]]; then
        echo "Error: cert/key files required" >&2
        exit 1
    fi
    mkdir -p /var/lib/pbx3sbc-admin/custom-tls
    cp "$cert_src" /var/lib/pbx3sbc-admin/custom-tls/fullchain.pem
    cp "$key_src" /var/lib/pbx3sbc-admin/custom-tls/privkey.pem
    chmod 640 /var/lib/pbx3sbc-admin/custom-tls/fullchain.pem /var/lib/pbx3sbc-admin/custom-tls/privkey.pem
    chown root:www-data /var/lib/pbx3sbc-admin/custom-tls/fullchain.pem /var/lib/pbx3sbc-admin/custom-tls/privkey.pem
    local php_sock
    php_sock=$(ls /run/php/php*-fpm.sock 2>/dev/null | head -1 || true)
    cmd_apply_nginx "$fqdn" "$webroot" "$php_sock" \
        /var/lib/pbx3sbc-admin/custom-tls/fullchain.pem \
        /var/lib/pbx3sbc-admin/custom-tls/privkey.pem
    set_app_url_https "$fqdn" "$webroot"
    echo '{"installed":true}'
}

cmd_custom_remove() {
    require_root
    local fqdn="$1"
    local webroot="$2"
    validate_fqdn "$fqdn"
    rm -f /var/lib/pbx3sbc-admin/custom-tls/fullchain.pem /var/lib/pbx3sbc-admin/custom-tls/privkey.pem
    if [[ -f "/etc/letsencrypt/live/${fqdn}/fullchain.pem" ]]; then
        local php_sock
        php_sock=$(ls /run/php/php*-fpm.sock 2>/dev/null | head -1 || true)
        cmd_apply_nginx "$fqdn" "$webroot" "$php_sock"
        set_app_url_https "$fqdn" "$webroot"
        echo '{"installed":false,"fallback":"letsencrypt"}'
    else
        echo "Error: removed custom cert; no Let's Encrypt cert to fall back to — re-run setup" >&2
        exit 1
    fi
}

CMD="${1:-}"
shift || true

case "$CMD" in
    status)
        cmd_status "${1:-}"
        ;;
    setup)
        cmd_setup "${1:-}" "${2:-}" "${3:-}"
        ;;
    renew)
        cmd_renew "${1:-}"
        ;;
    apply-nginx)
        cmd_apply_nginx "${1:-}" "${2:-}" "${3:-}" "${4:-}" "${5:-}"
        ;;
    custom-install)
        cmd_custom_install "${1:-}" "${2:-}" "${3:-}" "${4:-}"
        ;;
    custom-remove)
        cmd_custom_remove "${1:-}" "${2:-}"
        ;;
    *)
        echo "Usage: $0 status|setup|renew|apply-nginx|custom-install|custom-remove ..." >&2
        exit 1
        ;;
esac
